CREATE TABLE IF NOT EXISTS meals (
    id SERIAL PRIMARY KEY,
    food_plan_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_food_plan FOREIGN KEY(food_plan_id) REFERENCES food_plans(id) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS meals ENABLE ROW LEVEL SECURITY;